"""Add validation_snapshots table

Revision ID: 46e562f55a1a
Revises: 860ca3201fa0
Create Date: 2026-06-19 03:57:13.104878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e562f55a1a'
down_revision = '860ca3201fa0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_snapshots',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_key', sa.String(), nullable=False),
    sa.Column('snapshot_type', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate_pct', sa.Float(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('avg_return_pct', sa.Float(), nullable=False),
    sa.Column('largest_win', sa.Float(), nullable=False),
    sa.Column('largest_loss', sa.Float(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('fill_rate_pct', sa.Float(), nullable=False),
    sa.Column('chart_data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_index(op.f('ix_validation_snapshots_period'), 'validation_snapshots', ['period'], unique=False)
    op.create_index(op.f('ix_validation_snapshots_snapshot_key'), 'validation_snapshots', ['snapshot_key'], unique=True)
    op.create_index(op.f('ix_validation_snapshots_snapshot_type'), 'validation_snapshots', ['snapshot_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_snapshots_snapshot_type'), table_name='validation_snapshots')
    op.drop_index(op.f('ix_validation_snapshots_snapshot_key'), table_name='validation_snapshots')
    op.drop_index(op.f('ix_validation_snapshots_period'), table_name='validation_snapshots')
    op.drop_table('validation_snapshots')
    # ### end Alembic commands ###