"""nexa_intelligence_foundation

Revision ID: 52392d88fb39
Revises: 99f0ba1e9d0f
Create Date: 2026-06-07 01:09:48.939997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52392d88fb39'
down_revision = '99f0ba1e9d0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_events',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('impact', sa.String(), nullable=False),
    sa.Column('actual_value', sa.String(), nullable=True),
    sa.Column('forecast_value', sa.String(), nullable=True),
    sa.Column('previous_value', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_index(op.f('ix_economic_events_id'), 'economic_events', ['id'], unique=True)
    op.create_index(op.f('ix_economic_events_timestamp'), 'economic_events', ['timestamp'], unique=False)
    op.create_table('market_news_articles',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_index(op.f('ix_market_news_articles_id'), 'market_news_articles', ['id'], unique=True)
    op.create_index(op.f('ix_market_news_articles_published_at'), 'market_news_articles', ['published_at'], unique=False)
    op.create_table('market_sensitivity_scores',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('contributing_factors', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_index(op.f('ix_market_sensitivity_scores_id'), 'market_sensitivity_scores', ['id'], unique=True)
    op.create_index(op.f('ix_market_sensitivity_scores_symbol'), 'market_sensitivity_scores', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_sensitivity_scores_timestamp'), 'market_sensitivity_scores', ['timestamp'], unique=False)
    op.create_table('nlp_sentiments',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('sentiment_label', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_index(op.f('ix_nlp_sentiments_id'), 'nlp_sentiments', ['id'], unique=True)
    op.create_index(op.f('ix_nlp_sentiments_reference_id'), 'nlp_sentiments', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nlp_sentiments_reference_id'), table_name='nlp_sentiments')
    op.drop_index(op.f('ix_nlp_sentiments_id'), table_name='nlp_sentiments')
    op.drop_table('nlp_sentiments')
    op.drop_index(op.f('ix_market_sensitivity_scores_timestamp'), table_name='market_sensitivity_scores')
    op.drop_index(op.f('ix_market_sensitivity_scores_symbol'), table_name='market_sensitivity_scores')
    op.drop_index(op.f('ix_market_sensitivity_scores_id'), table_name='market_sensitivity_scores')
    op.drop_table('market_sensitivity_scores')
    op.drop_index(op.f('ix_market_news_articles_published_at'), table_name='market_news_articles')
    op.drop_index(op.f('ix_market_news_articles_id'), table_name='market_news_articles')
    op.drop_table('market_news_articles')
    op.drop_index(op.f('ix_economic_events_timestamp'), table_name='economic_events')
    op.drop_index(op.f('ix_economic_events_id'), table_name='economic_events')
    op.drop_table('economic_events')
    # ### end Alembic commands ###