"""initial_schema

Revision ID: 67de4f116742
Revises: 
Create Date: 2026-06-06 22:07:31.071554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67de4f116742'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_table('backtest_results',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('performance_summary', sa.JSON(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.pk_id'], name='fk_backtest_results_strategy_id', use_alter=True),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_table('equity_curves',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.pk_id'], name='fk_equity_curves_portfolio_id', use_alter=True),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_index(op.f('ix_equity_curves_portfolio_id'), 'equity_curves', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_equity_curves_timestamp'), 'equity_curves', ['timestamp'], unique=False)
    op.create_table('mandates',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('daily_loss_limit_pct', sa.Float(), nullable=False),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('leverage_limit', sa.Integer(), nullable=False),
    sa.Column('allowed_assets', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('kill_switch_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_index(op.f('ix_mandates_id'), 'mandates', ['id'], unique=True)
    op.create_table('reports',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('performance_metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.pk_id'], name='fk_reports_portfolio_id', use_alter=True),
    sa.PrimaryKeyConstraint('pk_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('risk_events',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.pk_id'], name='fk_risk_events_portfolio_id', use_alter=True),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_index(op.f('ix_risk_events_event_type'), 'risk_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_risk_events_portfolio_id'), 'risk_events', ['portfolio_id'], unique=False)
    op.create_table('strategies',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trades',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.pk_id'], name='fk_trades_portfolio_id', use_alter=True),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=True)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_tier', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('portfolios',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=30), nullable=False),
    sa.Column('mandate_pk_id', sa.Integer(), nullable=False),
    sa.Column('total_equity', sa.Float(), nullable=False),
    sa.Column('available_margin', sa.Float(), nullable=False),
    sa.Column('current_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mandate_pk_id'], ['mandates.pk_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_risk_events_portfolio_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_event_type'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_table('reports')
    op.drop_index(op.f('ix_mandates_id'), table_name='mandates')
    op.drop_table('mandates')
    op.drop_index(op.f('ix_equity_curves_timestamp'), table_name='equity_curves')
    op.drop_index(op.f('ix_equity_curves_portfolio_id'), table_name='equity_curves')
    op.drop_table('equity_curves')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###