"""Create initial tables

Revision ID: 6fc1be49da88
Revises: 
Create Date: 2026-06-01 15:49:59.022644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc1be49da88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('mandates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_leverage', sa.Float(), nullable=False),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('daily_loss_limit_pct', sa.Float(), nullable=True),
    sa.Column('weekly_loss_limit_pct', sa.Float(), nullable=True),
    sa.Column('max_position_size_pct', sa.Float(), nullable=True),
    sa.Column('max_trade_frequency_per_hour', sa.Integer(), nullable=True),
    sa.Column('allowed_assets', sa.JSON(), nullable=True),
    sa.Column('kill_switch_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role_tier', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('portfolios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('mandate_id', sa.String(), nullable=True),
    sa.Column('total_equity', sa.Float(), nullable=True),
    sa.Column('available_margin', sa.Float(), nullable=True),
    sa.Column('current_drawdown_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('period_start', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('period_end', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('risk_metrics', sa.JSON(), nullable=True),
    sa.Column('trades_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('triggered_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('closed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('risk_events')
    op.drop_table('reports')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('mandates')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###