"""Add Treasury Foundation tables

Revision ID: 860ca3201fa0
Revises: fc1ba4458177
Create Date: 2026-06-11 00:14:32.265914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860ca3201fa0'
down_revision = 'fc1ba4458177'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treasury_pools',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('target_allocation_pct', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_index(op.f('ix_treasury_pools_id'), 'treasury_pools', ['id'], unique=True)
    op.create_table('treasury_transactions',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('pool_pk_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pool_pk_id'], ['treasury_pools.pk_id'], ),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_index(op.f('ix_treasury_transactions_id'), 'treasury_transactions', ['id'], unique=True)
    op.create_index(op.f('ix_treasury_transactions_timestamp'), 'treasury_transactions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treasury_transactions_timestamp'), table_name='treasury_transactions')
    op.drop_index(op.f('ix_treasury_transactions_id'), table_name='treasury_transactions')
    op.drop_table('treasury_transactions')
    op.drop_index(op.f('ix_treasury_pools_id'), table_name='treasury_pools')
    op.drop_table('treasury_pools')
    # ### end Alembic commands ###