"""restore_audit_log_fields

Revision ID: 8e0522c05329
Revises: a40f9f4a687c
Create Date: 2026-06-06 22:56:19.712670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e0522c05329'
down_revision = 'a40f9f4a687c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('id', sa.String(length=30), nullable=False))
    op.add_column('audit_logs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=True)
    op.drop_column('audit_logs', 'details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'metadata_json')
    op.drop_column('audit_logs', 'description')
    op.drop_column('audit_logs', 'id')
    # ### end Alembic commands ###