"""restore_risk_events_fields

Revision ID: 99f0ba1e9d0f
Revises: fea23f9c5082
Create Date: 2026-06-06 23:28:51.274375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99f0ba1e9d0f'
down_revision = 'fea23f9c5082'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_events', sa.Column('id', sa.String(length=30), nullable=False))
    op.add_column('risk_events', sa.Column('severity', sa.String(), nullable=False))
    op.add_column('risk_events', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('risk_events', sa.Column('resolved', sa.Boolean(), nullable=False))
    op.alter_column('risk_events', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('ix_risk_events_id'), 'risk_events', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_events_id'), table_name='risk_events')
    op.alter_column('risk_events', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('risk_events', 'resolved')
    op.drop_column('risk_events', 'description')
    op.drop_column('risk_events', 'severity')
    op.drop_column('risk_events', 'id')
    # ### end Alembic commands ###