"""institutional_risk_framework

Revision ID: a40f9f4a687c
Revises: fa989ea93912
Create Date: 2026-06-06 22:36:29.546502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40f9f4a687c'
down_revision = 'fa989ea93912'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mandates', sa.Column('name', sa.String(), nullable=False))
    op.add_column('mandates', sa.Column('risk_tier', sa.String(), nullable=False))
    op.add_column('mandates', sa.Column('max_position_size_pct', sa.Float(), nullable=False))
    op.add_column('mandates', sa.Column('max_portfolio_exposure_pct', sa.Float(), nullable=False))
    op.add_column('mandates', sa.Column('max_leverage', sa.Float(), nullable=False))
    op.add_column('mandates', sa.Column('max_open_positions', sa.Integer(), nullable=False))
    op.add_column('mandates', sa.Column('restricted_assets_enabled', sa.Boolean(), nullable=False))
    op.add_column('mandates', sa.Column('kill_switch_enabled', sa.Boolean(), nullable=False))
    op.add_column('mandates', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('mandates', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('mandates', sa.Column('created_by_id', sa.String(), nullable=True))
    op.add_column('mandates', sa.Column('approved_by_id', sa.String(), nullable=True))
    op.add_column('mandates', sa.Column('effective_date', sa.DateTime(), nullable=False))
    op.add_column('mandates', sa.Column('previous_version_pk_id', sa.Integer(), nullable=True))
    op.alter_column('mandates', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    op.drop_index(op.f('ix_mandates_id'), table_name='mandates')
    op.create_index(op.f('ix_mandates_id'), 'mandates', ['id'], unique=False)
    op.create_foreign_key('fk_mandate_prev_version', 'mandates', 'mandates', ['previous_version_pk_id'], ['pk_id'], use_alter=True)
    op.drop_column('mandates', 'leverage_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mandates', sa.Column('leverage_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_mandate_prev_version', 'mandates', type_='foreignkey')
    op.drop_index(op.f('ix_mandates_id'), table_name='mandates')
    op.create_index(op.f('ix_mandates_id'), 'mandates', ['id'], unique=True)
    op.alter_column('mandates', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_column('mandates', 'previous_version_pk_id')
    op.drop_column('mandates', 'effective_date')
    op.drop_column('mandates', 'approved_by_id')
    op.drop_column('mandates', 'created_by_id')
    op.drop_column('mandates', 'updated_at')
    op.drop_column('mandates', 'created_at')
    op.drop_column('mandates', 'kill_switch_enabled')
    op.drop_column('mandates', 'restricted_assets_enabled')
    op.drop_column('mandates', 'max_open_positions')
    op.drop_column('mandates', 'max_leverage')
    op.drop_column('mandates', 'max_portfolio_exposure_pct')
    op.drop_column('mandates', 'max_position_size_pct')
    op.drop_column('mandates', 'risk_tier')
    op.drop_column('mandates', 'name')
    # ### end Alembic commands ###