"""add_market_data_table

Revision ID: fa989ea93912
Revises: 67de4f116742
Create Date: 2026-06-06 22:22:26.893275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa989ea93912'
down_revision = '67de4f116742'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data_ohlcv',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('timestamp', 'symbol')
    )
    op.create_foreign_key('fk_backtest_results_strategy_id', 'backtest_results', 'strategies', ['strategy_id'], ['pk_id'], use_alter=True)
    op.create_foreign_key('fk_equity_curves_portfolio_id', 'equity_curves', 'portfolios', ['portfolio_id'], ['pk_id'], use_alter=True)
    op.create_foreign_key('fk_reports_portfolio_id', 'reports', 'portfolios', ['portfolio_id'], ['pk_id'], use_alter=True)
    op.create_foreign_key('fk_risk_events_portfolio_id', 'risk_events', 'portfolios', ['portfolio_id'], ['pk_id'], use_alter=True)
    op.create_foreign_key('fk_trades_portfolio_id', 'trades', 'portfolios', ['portfolio_id'], ['pk_id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_trades_portfolio_id', 'trades', type_='foreignkey')
    op.drop_constraint('fk_risk_events_portfolio_id', 'risk_events', type_='foreignkey')
    op.drop_constraint('fk_reports_portfolio_id', 'reports', type_='foreignkey')
    op.drop_constraint('fk_equity_curves_portfolio_id', 'equity_curves', type_='foreignkey')
    op.drop_constraint('fk_backtest_results_strategy_id', 'backtest_results', type_='foreignkey')
    op.drop_table('market_data_ohlcv')
    # ### end Alembic commands ###