"""add_global_settings

Revision ID: fc1ba4458177
Revises: 52392d88fb39
Create Date: 2026-06-07 02:07:23.283910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1ba4458177'
down_revision = '52392d88fb39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('environment_state', sa.String(), nullable=False),
    sa.Column('extreme_bearish_threshold', sa.Float(), nullable=False),
    sa.Column('global_max_leverage', sa.Float(), nullable=False),
    sa.Column('default_commission_pct', sa.Float(), nullable=False),
    sa.Column('default_slippage_pct', sa.Float(), nullable=False),
    sa.Column('global_kill_switch_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_settings')
    # ### end Alembic commands ###