"""restore_report_type

Revision ID: fea23f9c5082
Revises: 8e0522c05329
Create Date: 2026-06-06 23:08:09.866231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea23f9c5082'
down_revision = '8e0522c05329'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('report_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'report_type')
    # ### end Alembic commands ###